/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package christmasgifts;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *Assessment.java
 * 5th December 2020
 * @author Ruby Lennon
 * Student Number: x19128355
 */
public class GiftGUI extends javax.swing.JFrame {
    //variable
    String recipientName, giftIdea, url;
    
    //declare array of objects
    Gift[] arr;
    
    //declare counter
    int count;
    /**
     * Creates new form GiftGUI
     */
    public GiftGUI() {
        initComponents();

        //create array
        arr = new Gift[10];
        
        //initialising counter to 0
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        recipientNameLbl = new javax.swing.JLabel();
        giftIdeaLbl = new javax.swing.JLabel();
        urlLbl = new javax.swing.JLabel();
        recipientNameTf = new javax.swing.JTextField();
        giftIdeaTf = new javax.swing.JTextField();
        urlTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLbl.setText("Christmas Gift Idea Application");

        recipientNameLbl.setText("Recipient Name:");

        giftIdeaLbl.setText("Gift Idea:");

        urlLbl.setText("URL:");

        addBtn.setText("Add Gift Idea");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display All Gift Ideas");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search by Recipient Name");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Gift Idea");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        readBtn.setText("View All Saved");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(readBtn)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(recipientNameLbl)
                                    .addComponent(giftIdeaLbl)
                                    .addComponent(urlLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(urlTf, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(giftIdeaTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipientNameTf, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleLbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipientNameLbl)
                    .addComponent(recipientNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giftIdeaLbl)
                    .addComponent(giftIdeaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLbl)
                    .addComponent(urlTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(readBtn))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //create gift object
        Gift g;
        
        //declare gift object
        g = new Gift();
        
        //get text from textfields
        recipientName= recipientNameTf.getText();
        giftIdea = giftIdeaTf.getText();
        url = urlTf.getText();
        
        //adding details to the object
        g.setRecipientName(recipientName);
        g.setGiftIdea(giftIdea);
        g.setUrl(url);
        
        //adding the object to the array
        arr[count] = g;
        //increment the counter
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //loop through the array of objects
        for(int i =0; i < arr.length; i = i +1){
            JOptionPane.showMessageDialog(null,"Recipient Name: "+arr[i].getRecipientName()+"\n Gift Idea: "+arr[i].getGiftIdea()+"\n URL: "+arr[i].getUrl());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchRecipientName = JOptionPane.showInputDialog(null,"Please enter a recipient name");
        
        for(int i = 0; i < arr.length; i = i +1){
            if(searchRecipientName.equalsIgnoreCase(arr[i].getRecipientName())){
                JOptionPane.showMessageDialog(null,"Recipient Name: "+arr[i].getRecipientName()+"\n Gift Idea: "+arr[i].getGiftIdea()+"\n URL: "+arr[i].getUrl());
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(recipientNameTf.getText().equals("")||giftIdeaTf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Sorry, you need to enter a recipient name and gift idea to delete an object");
        }
        else if(count==0){
            JOptionPane.showMessageDialog(null, "Sorry, there are no existing gift ideas at present");
        }
        else {
            recipientName = recipientNameTf.getText();
            giftIdea = giftIdeaTf.getText();
            url = urlTf.getText();
            
            for(int i = 0; i < count;i = i +1){
                if(arr[i].getRecipientName().equals(recipientName)&&arr[i].getGiftIdea().equals(giftIdea)){
                    arr[i]= arr[count-1];
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Deleted: "+recipientName+", "+giftIdea+", "+url+". There are now "+count+" gift ideas left.");
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"Sorry, the gift idea you are looking for cannot be found.");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        recipientName = recipientNameTf.getText();
        giftIdea = giftIdeaTf.getText();
        url = urlTf.getText();
        
        Gift g = new Gift();
        g.setRecipientName(recipientName);
        g.setGiftIdea(giftIdea);
        g.setUrl(url);
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(g);
            
            JOptionPane.showMessageDialog(null,"File written successfully");
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            Gift x;
            x = (Gift)oStream.readObject();
            
            JOptionPane.showMessageDialog(null,"Recipient Name: "+x.getRecipientName()+"\n Type: "+x.getGiftIdea()+"\n URL: "+x.getUrl());
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_readBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiftGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel giftIdeaLbl;
    private javax.swing.JTextField giftIdeaTf;
    private javax.swing.JButton readBtn;
    private javax.swing.JLabel recipientNameLbl;
    private javax.swing.JTextField recipientNameTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel urlLbl;
    private javax.swing.JTextField urlTf;
    // End of variables declaration//GEN-END:variables
}
